spring:
  application:
    name: demo

stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currencies: USD,EUR,GBP

payment:
  method: paypal

email:
  host: https://smtp.gmail.com
  port: 5761
